version: '3'

services:
    blogs:
        build: bloggs
        mem_limit: 512m
        ports:
            - "8080:8080"
        environment:
            DB_URL: jdbc:mysql://junction.proxy.rlwy.net:13326/BlogBack
            DB_USER_NAME: root
            DB_PASSWORD: NyKcugnSuPrqtPPRwDlRJFYicKFGalxl
            DB_NAME: BlogBack
        networks:
            - default
        restart: always

networks:
    default:
        driver: bridge
